### ISSUE TITLE
java.lang.IllegalArgumentException: Maximum transfer unit can be no smaller than 548

### ISSUE THREAD

**Issue by Magicode1** [DragonetMC/Dragonet#4]
`Exception in thread "main" java.lang.IllegalArgumentException: Maximum transfer unit can be no smaller than 548
	at net.marfgamer.jraknet.server.RakNetServer.<init>(RakNetServer.java:132)
	at net.marfgamer.jraknet.server.RakNetServer.<init>(RakNetServer.java:149)
	at net.marfgamer.jraknet.server.RakNetServer.<init>(RakNetServer.java:162)
	at net.marfgamer.jraknet.server.RakNetServer.<init>(RakNetServer.java:177)`
I get that error whenever I run the server after git cloning and mvn packaging the server

**Comment by TekkitCommando** [comment]
Something to do with the initialize function. I assume it's when you instantiate the new PE session. Might need to do some research on that.

**Comment by TheDiamondYT1** [comment]
Hmm, it works for me. But then again havent tested on the latest builds because i did those on a Kindle. What branch are you using?

**Comment by Magicode1** [comment]
Master I assume. I haven't added anything, just `git clone https://github.com/DragonetMC/Dragonet.git`

Also worth mentioning, I am on Linux.

**Comment by Magicode1** [comment]
We are using the port 19132, right? Just wondering because now I am getting a bind exception.

**Comment by TheDiamondYT1** [comment]
@Magicode1 Yes, 19132. Change it in the initialize function if you wish, i will make it configurable once the configuration branch is finished and merged

**Comment by Magicode1** [comment]
Figured it out :+1: It works now on my windows machine just fine. Weird. Maybe just a problem with my Linux Machine?

**Comment by TheDiamondYT1** [comment]
I'll leave this open in case its a Linux problem. But then again, it could just be *your* Linux machine.

**Comment by Fungie2134** [comment]
I have the same problem on any Linus distribution, so I think this is a linux - specific problem, maybe a java local ?
I tried fixing it but not working.

**Comment by DaMatrix** [comment]
I get the same issue with this AND SequinLand (nukkit with JRakNet), only on Linux. It's a JRakNet issue, maybe @MarfGamer could give us a hand?

**Comment by MarfGamer** [comment]
This is not a JRakNet issue, it's an actual implementation feature. If you like, I can change this.

**Comment by TheDiamondYT1** [comment]
@MarfGamer I literally copied the example in your JRakNet repi and edit the motd

**Comment by MarfGamer** [comment]
Really? In that case I will update the code immediately. Please link me to the file you copied and pasted so I can make sure I'm looking at the correct one. Also, it is best to let the server to decide the Maximum Transfer Unit for you. To do this, simply remove the MTU argument from the constructor and it should use the other two arguments you specified.

**Comment by MarfGamer** [comment]
If you cant find a constructor that lets you input everything without specifying the MTU, use RakNetUtils.getMaximumTransferUnit() as it uses the lowest MTU of all the network cards on the machine (Unless it is lower than the minimum MTU, in which case the card is not considered)

**Comment by TheDiamondYT1** [comment]
https://github.com/DragonetMC/Dragonet/blob/master/server/src/main/java/org/dragonet/server/network/pe/PENetworkSession.java#L45

**Comment by MarfGamer** [comment]
This seems very much to be a JRakNet issue. I would leave this issue open too however, so do not close it until I can make sure it is fixed. For now, you can manually set the MTU on your own by using the following lines of code: 
```java
int maximumTransferUnit;
try {
     maximumTransferUnit = NetworkInterface.getByInetAddress(InetAddress.getLocalHost()).getMTU();
} catch(Throwable e) {
     e.printStackTrace(); // This should not happen
     /* System.err.println("If you are a user, you can ignore this error"); */ // Optionally warn user here
     maximumTransferUnit = -1;
}
if(maximumTransferUnit < RakNet.MINIMUM_TRANSFER_UNIT) {
    maximumTransferUnit = RakNet.MINIMUM_TRANSFER_UNIT;
}
RakNetServer server = new RakNetServer(0 /* port */, 0 /* maximum connections */, null /* identifier */, maximumTransferUnit);
```
This is a manual workaround hack for now. Soon I'll try to clean up this error in the actual JRakNet code implementation tonight. I'll let you know when the new version is uploaded to maven.

**Comment by MarfGamer** [comment]
I just released an update that fixes this issue. It should now work on Linux systems. If the problem still persists, feel free to contact me! All you need to do is update the JRakNet version from 2.6.2 to 2.6.3 in your pom and rebuild.

**Comment by MarfGamer** [comment]
Anyone still here?

**Comment by TekkitCommando** [comment]
@MarfGamer Hi XD

**Comment by MarfGamer** [comment]
Has this issue been resolved?

**Comment by DaMatrix** [comment]
It works for me (tested on a Ubuntu 16.04 system that hadn't worked before) and was merged with #13

**Comment by MarfGamer** [comment]
Good to hear!
